### ISSUE TITLE
Japanese Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ja.reactjs.org#4]
# For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Take only one page at a time**.
3. Submit a PR!

Please check the [style guide](https://github.com/reactjs/ja.reactjs.org/blob/master/TRANSLATION.md) and [word list](https://github.com/reactjs/ja.reactjs.org/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80) to make sure translations are written in a consistent manner.

Also check out [the Crowdin repository](https://crowdin.com/project/react/ja) before starting translation of a new article. **Click and open each article** to see how much work has been actually done. **"0%" in the index page does not mean the article has not been translated!**

# For Reviewers

Before starting your thorough review, please make a comment in the individual PR page so that too many duplicate suggestions/comments will not happen at the same time. "Reviewers" section at the right means "those people will review *eventually*".

# Work List

(🏃 Work in Progress; 👀 In Review)

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@superyusuke) #55
* [x] Tutorial (@smikitky) #144

### Basics
  * [x] Hello World (@smikitky) (direct commit)
  * [x] Introducing JSX (@smikitky) (direct commit)
  * [x] Rendering Elements (@smikitky) (direct commit)
  * [x] Components and Props (@smikitky) (direct commit)
  * [x] State and Lifecycle (@smikitky) (direct commit)
  * [x] Handling Events (@smikitky) (direct commit)
  * [x] Conditional Rendering (@smikitky) (direct commit)
  * [x] Lists and Keys (@smikitky) (direct commit)
  * [x] Forms (@smikitky) (direct commit)
  * [x] Lifting State Up (@sasurau4) #15 
  * [x] Composition vs Inheritance (@Naturalclar) #5
  * [x] Thinking in React (@Nkzn) #16 
### API Reference
  * [x] React (@lightnet328) #47
  * [x] React.Component (@lightnet328) #127 
  * [x] ReactDOM (@gotchane) #45
  * [x]  ReactDOMServer (@sasurau4) #114 
  * [x] DOM Elements (@kn3ny) #12
  * [x] SyntheticEvent (@summertree128) #43
  * [x]  Test Utilities (@takanorip) #57
  * [x] Shallow Renderer (@sakito21) #56
  * [x] Test Renderer (@queq1890) #11
  * [x] JS Environment Requirements (@saitoeku3) #9
  * [x] Glossary (@potato4d) #2 #21

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml #144
* [x] docs/nav.yml (@potato4d) #149

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@Naturalclar) #63
* [x] Add React to a Website (@sato11) #19
* [x] Create a New React App (@kik4) #14
* [x] CDN Links (@kik4) #13

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

* [x] Hooks (@smikitky)
  * [x] Introducing Hooks #18
  * [x] Hooks at a Glance #48
  * [x] Using the State Hook #51
  * [x] Using the Effect Hook #54
  * [x] Rules of Hooks #64
  * [x] Building Your Own Hooks #65
  * [x] Hooks API Reference #130
  * [x] Hooks FAQ #115

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.

* [x] Warnings (@uehaj) #50
  * [x] dont-call-proptypes
  * [x] invalid-aria-prop
  * [x] legacy-factories
  * [x] refs-must-have-owner
  * [x] special-props
  * [x] unknown-prop
  * [x] invalid-hook-call-warning (new)

### Advanced Guides

* [x] Accessibility (@sasurau4) #99
* [x] Code-Splitting (@atsumine) #58
* [x] Context (@locol23) #59
* [x] Error Boundaries (@uenitty) #81
* [x] Forwarding Refs (@satotake)
* [x] Fragments (@shooontan) #92
* [x] Higher-Order Components (@satotake) #103
* [x] Integrating with Other Libraries (@thayashi) #117
* [x] JSX In Depth (@sato11) #62
* [x] Optimizing Performance (@uehaj) #122
* [x] Portals (@fsubal) #44
* [x] React Without ES6 (@ginpei) #53
* [x] React Without JSX (@hassi32) #62
* [x] Reconciliation (@km-tr) #101
* [x] Refs and the DOM (@y-temp4) #52
* [x] Render Props (@ossan-engineer) #49
* [x] Static Type Checking (@Naturalclar) #179
* [x]  Strict Mode (@notherno)
* [x] Typechecking With PropTypes (@Naturalclar) #67
* [x] Uncontrolled Components (@kik4)
* [x] Web Components (@Naturalclar) #102

### FAQ

* [x] AJAX and APIs (@ossan-engineer) #10
* [x] Babel, JSX, and Build Steps (@ossan-engineer) #93
* [x] Passing Functions to Components (@ossan-engineer) #111
* [x] Component State (@ginpei) #105
* [x] Styling and CSS (@Naturalclar) #104
* [x] File Structure (@syug) #120
* [x] Versioning Policy (@37108) #121
* [x] Virtual DOM and Internals (@syug) #132

### Testing :new:

* [x] Testing Overview (@taneba) #241 
* [x] Testing Recipes (@smikitky) #261
* [x] Testing Environments (@smikitky) #262

### Contributing

Priority: Low

* [x] How to Contribute (@oimo23) #123
* [x] Codebase Overview (@thayashi)
* [x] Implementation Notes (@y-yeah) #178
* [x] Design Principles (@hand-dot) #133

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor @potato4d
* [ ] CodeExample @potato4d
* [ ] ErrorDecoder @potato4d 
* [x] LayoutFooter #151
* [x] LayoutHeader
* [x] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* Blog
* Community

**Comment by Naturalclar** [comment]
I'd like to work on `Composition vs Inheritance`

**Comment by smikitky** [comment]
@Naturalclar Thank you! Probably you can use the Crowdin's work as a base. We have not established a formal reviewing process, but once you've made a PR, I or someone will take a look.

**Comment by potato4d** [comment]
As a model of translation, I think I want to work on a tutorial

**Comment by tesseralis** [comment]
@potato4d have you finished the glossary yet?

**Comment by potato4d** [comment]
After I finished translating glossary, it was meant as an example of translation of that glossary!

**Comment by Naturalclar** [comment]
@smikitky Thank you! I've made a [PR](#5) for translation of composition-vs-inheritance based on the translation on Crowdin
#5

**Comment by tesseralis** [comment]
@smikitky  I think I'll be able to handle the bot myself -- we'll probably end up forking che-tsumi so it'll be easier to customize. @potato4d I would still like your help though -- I'll ask you some questions in email :)

**Comment by smikitky** [comment]
For now, 

- Please do NOT modify link URLs in the original markdown even if there is a Japanese equivalent (using the Japanese version of an MDN/Wikipedia article, etc)
- Please do NOT worry about anchor names, just translate the heading text (reactjs/reactjs.org#1608)

**Comment by tesseralis** [comment]
@smikitky I think you can edit my issue with these additional notifications.

Why shouldn't we translate the external links? I'm curious because someone on the Spanish translation team was asking.

**Comment by tesseralis** [comment]
I don't think so... It depends on whether those links exist / are high quality in each language, right? Like, Japanese Wiki might have a good article on "declarative programming" but maybe Russian doesn't?

**Comment by tesseralis** [comment]
Will think of a way to do general translation guidelines.

**Comment by tesseralis** [comment]
@potato4d do you have any thoughts from your experience with vue?

**Comment by smikitky** [comment]
This is something we have to eventually discuss in the main repo. But React doc currently has literally hundreds of English-only external links (to Stack Overflow questions, YouTube videos, personal blog articles, etc), which is atypical as the official documentation of a large library. I feel changing only a small part of them on an ad-hoc basis might not be a manageable option at least in the short term.

**Comment by tesseralis** [comment]
Sure, do you want to leave a comment on the main issue? Or if you want it to just be among translators I created a parent group for the internationalization effort: https://github.com/orgs/reactjs/teams/reactjs-org-internationalization

**Comment by tesseralis** [comment]
I don't think it's "ad hoc" to have the rule:

"If this link is for technical documentation and there is a high quality translation, link to the translation. Otherwise, keep the original English link."

There are copious links to non-translateable things like YouTube videos and StackOverflow and I think that is a issue to be handled by the English repo writers, but I don't think that should be a blocker.

**Comment by potato4d** [comment]
@smikitky 
Since it seems better to prioritize the setting of Bot, it may be better to ask smikitky for the tutorial.
Could you please?

@tesseralis  @smikitky

In the case of Vue document, when I find a document translated by MDN etc., I am changing the link.

For example, most people reading Japanese documents are Japanese.
And, in most cases the Japanese are seeking Japanese document.

**Comment by potato4d** [comment]
I just submitted a pull request to introduce TextLint.
If you have an opinion, please comment.

https://github.com/reactjs/ja.reactjs.org/pull/6

**Comment by smikitky** [comment]
Okay, I'll take care of the tutorial.

**Comment by Nkzn** [comment]
May I take `Thinking in React` ?

**Comment by smikitky** [comment]
@Nkzn Yes, please!

**Comment by lightnet328** [comment]
May I take `React` and `React.Component`?

**Comment by potato4d** [comment]
@lightnet328 
Yes, please!
thanks!

**Comment by ossan-engineer** [comment]
Can I take `FAQ` ?

**Comment by saitoeku3** [comment]
Could I take `JS Environment Requirements` ?

**Comment by sakito21** [comment]
I'd like to work on `Shallow Renderer`

**Comment by smikitky** [comment]
@saitoeku3 @sakito21 Thank you!

**Comment by takanorip** [comment]
I have some questions.

1. Why we should check the old translation? I think it is too old.
2. How do we check the quality of the new translation? How is the reviewer determined?

If I shouldn't discuss here, change the place.

**Comment by superyusuke** [comment]
Home page ってまだ空いてますか？やります。

**Comment by smikitky** [comment]
@takanorip @superyusuke Thank you for your interest.

1. It depends on the article you're referring to. Some pages are already nearly 100% complete on Crowdin. In addition, the translation there are more or less reviewed with consistency in mind by more than one person, so it's safer to start based on it whenever possible. Still, you can always ignore some (or all) of them if you want.
2. This fork started _yesterday_, and there is no established workflow yet. Tentatively, @tesseralis assigned me as the primary reviewer/maintainer, and I am willing to check every PR. I was also the person who once completed the translation at Crowdin. Honestly speaking, I did not expect this enthusiasm, so someone who wants to focus on quality assurance can nominate themselves as a dedicated reviewer.

My top priority is to make a translation guide (including style guideline).

**Comment by queq1890** [comment]
May I work on `Test Renderer`? 👀

**Comment by potato4d** [comment]
@takanorip @superyusuke
(As additional information) see https://github.com/reactjs/ja.reactjs.org/issues/2 and https://github.com/reactjs/ja.reactjs.org/pull/6 and https://github.com/reactjs/ja.reactjs.org/issues/3
If you have an opinion, please comment!

**Comment by smikitky** [comment]
@ossan-engineer  Sorry for the late reply. よろしくお願いします.
@superyusuke Thank you. ホームページとなると一段厳しくみんなでクオリティチェックされる可能性が高いのでレビューは気長にお付き合いください。
@queq1890 Yes, thank you!

**Comment by kn3ny** [comment]
Can I take `DOM Elements`?

**Comment by gotchane** [comment]
May I work on `ReactDOM`?

**Comment by euxn23** [comment]
May I work on `ReactDOMServer`?

**Comment by takanorip** [comment]
@smikitky 
Thanks for your answer.
I translate some documents and review other translation for now.

I will translate `Test Utilities`.

**Comment by Naturalclar** [comment]
I'd like to work on `Installation` ([getting-started.md](https://github.com/reactjs/ja.reactjs.org/blob/master/content/docs/getting-started.md))

**Comment by watilde** [comment]
`Contributing` seems to be done p much already on crowdin.

**Comment by summertree128** [comment]
May I work on `SyntheticEvent` ?

**Comment by tesseralis** [comment]
Hi everyone!

I'm simply amazed at the incredible effort you've put in so far. I updated the issue with a stronger guideline on the rest of the sections, as suggested by @gaearon.

@ossan-engineer, the FAQ is composed of multiple sections. Could you start off with one and open up the rest to other people?

**Comment by uehaj** [comment]
Hi!
May I take "Add React to a Website" ? If there is other parts to be worked, please inform me.

**Comment by tesseralis** [comment]
@uehaj Could you take one of the "warnings" first? These are the pages that are linked in the console warnings that happen, and they're useful for people to look up!

**Comment by uehaj** [comment]
> @uehaj Could you take one of the "warnings" first? These are the pages that are linked in the console warnings that happen, and they're useful for people to look up!

I got it! Ill tackle the ones.

**Comment by kik4** [comment]
May I take `CDN Links`?

**Comment by ossan-engineer** [comment]
@tesseralis Sure! I'm starting off with faq-ajax. I'd really aprreciate it if you list and open up other FAQs.

**Comment by smikitky** [comment]
@summertree128 @uehaj @kik4 Updated the list. よろしくお願いします

**Comment by ytorii** [comment]
素晴らしい。
一昨年のCrowdInでは作業者が数人しか居なかったけど、今回はこんなにContributeする方々が居るとは！

@smikitky 
自分もまた時間作って翻訳に参加させて頂きます。

**Comment by sato11** [comment]
Hi everyone!

I'm thrilled to see what's going on here and I'd really like to lend a hand.
Just wondered: @uehaj are you taking the whole `Warnings` section? If it's too much work to be done during this weekend, tell me so I can be of help.

@tesseralis @smikitky 
While waiting for his answer, I'm working on `Add React to a Website` part as it seems vacant. Okay with you?

**Comment by smikitky** [comment]
Added the list of Advanced Guide / Contributing articles you can work on this weekend :)

---
@sato11 Thank you, assigned you to add-react-to-a-website. Each page under `warnings` are relatively small, so one person might handle that.

**Comment by fsubal** [comment]
May I take `Portals` in Advanced guides ?

**Comment by smikitky** [comment]
@fsubal 渋いチョイスですねｗ　よろしくお願いします

**Comment by sato11** [comment]
So are we stepping into advanced section?
Having finished the draft above I'd like to take `JSX In Depth` part, may I?

**Comment by smikitky** [comment]
@sato11 Yes, translating Advanced Topics was an extended goal, but since we've already run out of articles in Basics, I think we can move on.

**Comment by smikitky** [comment]
@shooontan Yes, thank you!

**Comment by locol23** [comment]
May I take `Context` in Advanced Guides?

**Comment by smikitky** [comment]
@y-temp4 @atsumine @uenitty @locol23 Thank you, please start translations.

**Comment by ginpei** [comment]
Hi I'd love to join. Can I take React Without ES6 in Advanced Guides?

**Comment by uehaj** [comment]
> I'm thrilled to see what's going on here and I'd really like to lend a hand.
> Just wondered: @uehaj are you taking the whole `Warnings` section? If it's too much work to be done during this weekend, tell me so I can be of help.

Sorry for late responding and thanks for consideration. I have done whole warnings section.
Textlint is passes the last PR commit.

**Comment by hassi32** [comment]
Hi, can I take React without JSX ?

**Comment by uehaj** [comment]
May I take "Optimizing Performance" ?

**Comment by smikitky** [comment]
主にレビューでご協力くださっている方へ：

「今からレビューをするぞ」というところで、そのようにコメントで宣言していただくようお願いします。レビューはとても大切ですが、2人が全く同時にレビューすると「同じ指摘が重複して単純に労力の無駄」「コメント量が約2倍になって見づらい」「万一指摘が矛盾していたときに面倒」といったことになりがちですので、まずは1名が宣言した上で全体のレビューをしっかりやるのが効率的だと思います。よろしくお願いします。

CC @koba04 @potato4d @takanorip @sasurau4 

（とはいえこんな心配しないといけないのはとても有り難いです）

**Comment by potato4d** [comment]
Approve は一応個人のオピニオンとして持っておいたほうが安全かなぁという印象がありました。特に件数が増えてくると重複してる部分を見るのが怪しくなりがちなので、誰かのレビュー(というよりその人からのレビュー対応)が落ち着いた頃にやったほうが、作業者の心理的にも優しそうな気がしています

**Comment by koba04** [comment]
@smikitky @potato4d なるべく明確にルール化されている方が、レビュイー/レビュアーにとっても安心だと思います。Approve自体は権限なくても示すことが出来るので、下記のフローを繰り返してマージボタンを押せる状態（権限ある人の 2 Approve）になったらマージするのは如何でしょう。

1. レビュアー レビュー宣言
1. レビュアー レビュー
1. 作業者 レビュー対応
1. (2〜3を繰り返し) レビュアー Approve
1. マージの条件を満たした場合はマージ、そうでなければ別のレビュアーが条件を満たすまで1〜4を繰り返す

**Comment by koba04** [comment]
レビュー中か示すのは、コメントだと見落としが発生しそうなので、ラベルをつける運用でどうでしょうか？
「in review」というラベルを作ってみました。
レビュー開始時に付与して、レビューが終わった(Approveした)ら外す形で。

**Comment by smikitky** [comment]
とりあえず #61 に移動して続けましょう…

**Comment by Naturalclar** [comment]
Could I take `dont-call-proptypes` in the Warnings section?

**Comment by sasurau4** [comment]
I'll work on ` Rules of Hooks` !

**Comment by smikitky** [comment]
@sasurau Hooks-related articles are [already translated](https://github.com/smikitky/react-doc-jp-temp/tree/master/content/docs), so could you choose another article?

**Comment by sasurau4** [comment]
@smikitky Oh, I misunderstood! 💦 
I take `Accessibility` instead.

**Comment by notherno** [comment]
Hello, could I work on `Strict Mode` on Advanced Guides?

**Comment by Naturalclar** [comment]
I'd like to work on `Web Components`

**Comment by ossan-engineer** [comment]
Hi, can I take `Babel, JSX, and Build Steps` ?

**Comment by tesseralis** [comment]
Hi all! I just synced from the original repo and there's some files that need re-translating! (Look for the `<<<<<< HEAD` comments)

https://github.com/reactjs/ja.reactjs.org/pull/91

**Comment by smikitky** [comment]
#91 で、先週のフォークからの1週間で upstream (本家 reactjs.org) で起きたドキュメントの更新に対応するコミットが大量にマージされます。が、とりあえず翻訳絡みで影響があるのは Test Utils (#57, @takanorip) とフック絡みの各種記事 (@smikitky) のみです。他の方は現在の作業をそのまま続けて問題ありません。よろしくお願いします。

**Comment by km-tr** [comment]
Can I take `Reconciliation` ?

**Comment by smikitky** [comment]
@km-tr よろしくお願いします。Crowdinの翻訳をベースにする場合「突き合わせ」という訳語が使われていると思いますが、「更新検出処理」ないし「リコンシリエーション」で行くことになりましたのでご確認願います。
https://github.com/reactjs/ja.reactjs.org/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80

**Comment by ossan-engineer** [comment]
Hi, can I take `Passing Functions to Components` ?

**Comment by smikitky** [comment]
⚠️ 各位、特に現在進行中のPRをお持ちの方 (@uenitty @Naturalclar @sato11 @locol23 @atsumine @takanorip @superyusuke @uehaj @lightnet328)：

reactjs/reactjs.org#1608 と、それに対応する #96 の作業が完了し、すべての見出しに明示的にアンカー名が入るようになりました。以下のようなシンタックスです。これにより、ページ間・ページ内のすべてのリンクがURLを全く変えずに動作するようになります。

```
## Try React {#try-react}

### What does const [thing, setThing] = useState() mean? {#destructuring}
```

翻訳する時は、アンカー部分はそのまま残して、見出し本文のみを翻訳してください。

```
## React を試す {#try-react}

### const [thing, setThing] = useState() という記法の意味は？ {#destructuring}
```

まだ master にマージされていない PR をお持ちの方は、ちょっとしたコンフリクト解決作業をお願いします。ブランチの rebase と force-push による作業がお勧めです。殆どの方には釈迦に説法で申し訳ありませんが、[こちらで](https://github.com/reactjs/ja.reactjs.org/wiki/Git%E4%BD%9C%E6%A5%AD%E3%81%AE%E3%83%92%E3%83%B3%E3%83%88)も軽く説明しています。お手数ですがよろしくお願いします。

本日朝時点までにマージ済みの翻訳については、既にアンカーが付いていますので特段の作業は不要です。

これで無事 v16.8 リリース（Hook 導入）と ID 導入という大きな作業を乗り越えたので、ここから先に大きな改変やマージはそうそう起きないと思います。よろしくお願いします。

**Comment by tesseralis** [comment]
Excellent work everyone! We're almost done with the core pages!

@lightnet328 @euxn23 how is the progress on your pages? It's been a while, if you are unable to complete those, please let us know so we can reassign those to other people.

**Comment by Naturalclar** [comment]
I'd like to work on `Styling and CSS`

**Comment by satotake** [comment]
I would like to translate `Higher-Order Components` section.

**Comment by Naturalclar** [comment]
I'd like to work on `Static Type Checking`

**Comment by ginpei** [comment]
I'm going to take Component State in FAQ.

**Comment by tesseralis** [comment]
I'm going to open up ReactDOMServer since @euxn23 hasn't responded. Would anyone like to take it?

**Comment by km-tr** [comment]
I'd like to work on `Virtual DOM and Internals`

**Comment by kik4** [comment]
May I take `Uncontrolled Components`?

**Comment by thayashi** [comment]
May I take  `Integrating with Other Libraries`?

**Comment by smikitky** [comment]
**お知らせ**　半角スペースにまつわる細かいルールについてお手数をおかけしていましたが、自動でこれらを発見できる（`--fix` による自動修正はまだできない） textlint を #98 で導入しました。[リベース](https://github.com/reactjs/ja.reactjs.org/wiki/Git%E4%BD%9C%E6%A5%AD%E3%81%AE%E3%83%92%E3%83%B3%E3%83%88#rebase-%E3%81%A8-force-push)して取り込んでいただければ作業が少し楽になると思います。よろしくお願いします。

**Comment by lightnet328** [comment]
@tesseralis 
Sorry for the late reply.
I will continue to translate on another page as well.

**Comment by syug** [comment]
Hi, can I take `File structure`?

**Comment by sasurau4** [comment]
I'd like to work on `ReactDOMServer` :+1:

**Comment by satotake** [comment]
I am trying `Forwarding Refs`

**Comment by 37108** [comment]
I'd like to work `Versioning Policy`
can I take this?

**Comment by oimo23** [comment]
Hi, I'd like to work on `How to Contribute`

**Comment by hand-dot** [comment]
Hi, Can I take `Design Principles` ?

**Comment by thayashi** [comment]
May I take `Codebase Overview`?

**Comment by km-tr** [comment]
https://github.com/reactjs/ja.reactjs.org/issues/4#issuecomment-462094876 `Virtual DOM and Internals`
I wanted to translate, but since my work has become busy, can you reassign it to other people?
@smikitky @tesseralis

**Comment by syug** [comment]
Then, may I take `Virtual DOM and Internals`?

**Comment by tesseralis** [comment]
@smikitky how goes the tutorial?

Good work everyone! Just a couple more reviews and we're ready to go!

Also, look what @bvaughn set up: https://ja.reactjs.org

**Comment by potato4d** [comment]
Since https://ja.reactjs.org became available, I'll translate sequential navigation.

**Comment by y-yeah** [comment]
Hey guys, mat I take `Implementation Notes`?

**Comment by smikitky** [comment]
"Core Pages" の翻訳が終わりました！

**Comment by tesseralis** [comment]
おめでとうございます！ 🎉

<img width="338" alt="screen shot 2019-03-01 at 4 29 45 pm" src="https://user-images.githubusercontent.com/1278991/53673921-4c2af280-3c3f-11e9-971a-af46b999650e.png">

**Comment by smikitky** [comment]
@Naturalclar @y-yeah How is the progress? If you don't enough time, we can release the assignment and have others do the job.

**Comment by y-yeah** [comment]
> @Naturalclar @y-yeah How is the progress? If you don't enough time, we can release the assignment and have others do the job.

**Implementation notes** will be done this Friday. Sorry about taking a while!

**Comment by y-yeah** [comment]
Finished translating **implmentation notes**!

**Comment by Naturalclar** [comment]
>@Naturalclar @y-yeah How is the progress? If you don't have enough time, we can release the assignment and have others do the job.

Sorry for the delay! I'll work on it tonight (JST) :bow:

**Comment by G-N555** [comment]
Can I translate `external-resources`?
Is this required to do that?

**Comment by potato4d** [comment]
@G-N555 
Yes, please!

**Comment by G-N555** [comment]
I've done translation! Please check when you have time.
Btw, can I translate the rest of community after that?

**Comment by taneba** [comment]
@tesseralis 
How about TESTING?
Can I please start translating "testing"?

**Comment by smikitky** [comment]
@taneba Thank you, please proceed with them.

(tesseralisさんは全言語の統括なので日本語の記事についてはメンテナにお願いします)

**Comment by taneba** [comment]
@smikitky Thanks, I want to begin with [https://reactjs.org/docs/testing.html](https://reactjs.org/docs/testing.html). If nobody take the rest of it until I finish it, I will take some more.

> (tesseralisさんは全言語の統括なので日本語の記事についてはメンテナにお願いします)
なるほどです、承知しました！

**Comment by potato4d** [comment]
I'll start translating `Components`.

**Comment by smikitky** [comment]
こちらは #262 がマージされしだい close します。Concurrent Mode に関係する翻訳は #274 でお願いします。
